// Generated by CoffeeScript 1.8.0
var Dictionary, pbook;

Dictionary = function() {
  this.datastore = [];
  this.add = function(key, value) {
    this.datastore[key] = value;
  };
  this.find = function(key) {
    return this.datastore[key];
  };
  this.remove = function(key) {
    delete this.datastore[key];
  };
  this.showAll = function() {
    var key, _i, _len, _ref;
    _ref = Object.keys(this.datastore).sort();
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      key = _ref[_i];
      console.log(key + "->" + this.datastore[key]);
    }
  };
  this.count = function() {
    var key, n, _i, _len, _ref;
    n = 0;
    _ref = Object.keys(this.datastore);
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      key = _ref[_i];
      ++n;
    }
    return n;
  };
  this.clear = function() {
    var key, _i, _len, _ref, _results;
    _ref = Object.keys(this.datastore);
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      key = _ref[_i];
      _results.push(delete this.datastore[key]);
    }
    return _results;
  };
};

pbook = new Dictionary();

pbook.add('mike', 123);

pbook.add('david', 345);

pbook.add('cynthia', 567);

pbook.showAll();

pbook.remove('mike');

pbook.clear();

console.log('----');

pbook.showAll();
