// Generated by CoffeeScript 1.8.0
var List, names;

List = function() {
  this.listSize = 0;
  this.pos = 0;
  this.dataStore = [];
  this.clear = function() {
    delete this.dataStore;
    this.dataStore = [];
    this.listSize = this.pos = 0;
  };
  this.toString = function() {
    return this.dataStore;
  };
  this.insert = function(element, after) {
    var insertPos;
    insertPos = this.find(after);
    if (insertPos > -1) {
      this.dataStore.splice(insertPos + 1, 0, element);
      ++this.listSize;
      return true;
    }
    return false;
  };
  this.append = function(element) {
    this.dataStore[this.listSize++] = element;
  };
  this.remove = function(element) {
    var fountAt;
    fountAt = this.find(element);
    if (fountAt > -1) {
      this.dataStore.splice(fountAt, 1);
      --this.listSize;
      return true;
    }
    return false;
  };
  this.front = function() {
    this.pos = 0;
  };
  this.end = function() {
    this.pos = this.listSize - 1;
  };
  this.prev = function() {
    if (this.pos > 0) {
      --this.pos;
    }
  };
  this.next = function() {
    if (this.pos < this.listSize - 1) {
      ++this.pos;
    }
  };
  this.length = function() {
    return this.listSize;
  };
  this.currPos = function() {
    return this.pos;
  };
  this.moveTo = function(position) {
    return this.pos = position;
  };
  this.getElement = function() {
    return this.dataStore[this.pos];
  };
  this.contains = function(element) {
    var i, _i, _ref;
    for (i = _i = 0, _ref = this.dataStore.length; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
      if (this.dataStore[i] === element) {
        return true;
      }
    }
    return false;
  };
  this.find = function(element) {
    var i, _i, _ref;
    for (i = _i = 0, _ref = this.dataStore.length; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
      if (this.dataStore[i] === element) {
        return i;
      }
    }
    return -1;
  };
};

names = new List();

names.append('jfeng');

names.append('huifang');

names.append('panpan');

names.append('brain');

console.log(names);

console.log(names.length());

console.log(names.toString());

names.front();

console.log(names.getElement());

names.next();

console.log(names.getElement());
