// Generated by CoffeeScript 1.8.0
var Queue;

Queue = function() {
  this.dataStore = [];
  this.enqueue = function(element) {
    this.dataStore.push(element);
  };
  this.dequeue = function() {
    return this.dataStore.shift();
  };
  this.front = function() {
    return this.dataStore[0];
  };
  this.back = function() {
    return this.dataStore[this.dataStore.length - 1];
  };
  this.toString = function() {
    var i, retStr, _i, _ref;
    retStr = "";
    for (i = _i = 0, _ref = this.dataStore.length; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
      retStr += this.dataStore[i] + "\n";
    }
    return retStr;
  };
  this.empty = function() {
    if (this.dataStore.length === 0) {
      return true;
    } else {
      return false;
    }
  };
};
