// Generated by CoffeeScript 1.8.0
var Stack, popped, s;

Stack = function() {
  this.dataStore = [];
  this.top = 0;
  this.push = function(element) {
    this.dataStore[this.top++] = element;
  };
  this.pop = function() {
    return this.dataStore[--this.top];
  };
  this.peek = function() {
    return this.dataStore[this.top - 1];
  };
  this.length = function() {
    return this.top;
  };
  this.clear = function() {
    this.top = 0;
  };
};

s = new Stack();

s.push('jfeng');

s.push('huifang');

s.push('zihan');

console.log(s.length());

console.log(s.peek());

s.push('test');

console.log(s.peek());

popped = s.pop();

console.log(popped);
